### ISSUE TITLE
Add template that uses the Serverless framework for deployment

### ISSUE THREAD

**Issue by jankoenig** [jovotech/jovo-templates#20]
Including creating the right permissions, lambda, and DynamoDB for e.g. AWS

https://serverless.com/

**Comment by shouxian92** [comment]
Hi @jankoenig i'm interested to pick up this issue

**Comment by jankoenig** [comment]
Cool! Let me know if you need more info.
I started playing with it a few months ago. Here's part of the `serverless.yml` (I commented out some things and am not sure if everything works):

```yml
service: jovo-project-name  # Update

custom:
  defaultStage: dev
  currentStage: ${opt:stage, self:custom.defaultStage}

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${self:custom.currentStage}
  # iamRoleStatements:
  #   - Effect: "Allow"
  #     Action:
  #     - dynamodb: GetItem
  #     - dynamodb: PutItem
  #     - dynamodb: CreateTable
  #     Resource: "arn:aws:dynamodb:*:*:table/*"

# Define service wide environment variables here
# environment:
#   STAGE: ${self:custom.currentStage}

package:
 include:
   - index.js
   - app/**
 exclude:
   - platforms/**
   - models/**

functions:
  app:
    handler: index.handler
    events:
      # - alexaSkill: ${file(./app.json):stages.${self:custom.currentStage}.alexaSkill.skillId}
      
      # API Gateway
      # - http:
      #     method: post

    # Define function environment variables here
    environment:
      STAGE: ${self:custom.currentStage}
```
